stages:
  - build
  - test
  - success
  - failure

before_script:
  - uname -a

# simple builds

gcc-5:
  stage: build
  script:
  - ./tools/ci/jobs/gcc5.sh --enable-werror
  image: debian:unstable

# tests

plugin_validator:
  stage: test
  script:
  - ./tools/ci/jobs/validate.sh
  image: debian:unstable

# reports

success:
  stage: success
  script:
  - echo "do nothing"
  image: debian:unstable
  when: on_success

failure:
  stage: failure
  script:
  - echo "do nothing"
  image: debian:unstable
  when: on_failure
